# Generated by Django 5.0.2 on 2025-08-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('55+', '55+')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='budget',
            field=models.CharField(blank=True, choices=[('low', 'Low (< 50€/month)'), ('moderate', 'Moderate (50-150€/month)'), ('high', 'High (> 150€/month)')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pathologies',
            field=models.TextField(blank=True, help_text='Any skin conditions or medical concerns'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_completed',
            field=models.BooleanField(default=False, help_text='Whether payment was completed for Premium upgrade'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination'), ('sensitive', 'Sensitive')], max_length=50),
        ),
    ]
