# Generated by Django 5.0.2 on 2025-08-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_age_range_userprofile_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies_list',
            field=models.JSONField(blank=True, default=list, help_text='Liste des allergies connues'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies_other',
            field=models.CharField(blank=True, help_text='Autres allergies', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dermatological_conditions',
            field=models.JSONField(blank=True, default=list, help_text='Pathologies dermatologiques connues'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dermatological_other',
            field=models.CharField(blank=True, help_text='Autres pathologies dermatologiques', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='objectives',
            field=models.JSONField(blank=True, default=list, help_text='Objectifs principaux de la routine'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='product_style',
            field=models.CharField(blank=True, choices=[('natural', 'Bio / Naturel'), ('pharmacy', 'Pharmacie / Dermatologique'), ('luxury', 'Luxe / Haut de gamme'), ('minimalist', 'Minimaliste')], help_text='Style de produits préféré', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='routine_frequency',
            field=models.CharField(blank=True, choices=[('quick', 'Rapide (≤ 5 min)'), ('standard', 'Standard (10–20 min)'), ('comprehensive', 'Complète (20–30 min)')], help_text='Fréquence souhaitée de la routine', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='routine_type',
            field=models.CharField(blank=True, choices=[('morning', 'Matin'), ('evening', 'Soir'), ('custom', 'Personnalisée')], help_text='Type de routine préféré', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skin_concerns_list',
            field=models.JSONField(blank=True, default=list, help_text='Liste des problèmes de peau (acne, aging, dryness, etc.)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age_range',
            field=models.CharField(blank=True, choices=[('under18', 'Moins de 18 ans'), ('18-25', '18–25 ans'), ('26-35', '26–35 ans'), ('36-45', '36–45 ans'), ('46-60', '46–60 ans'), ('60plus', '60+ ans')], max_length=10),
        ),
    ]
