# Generated by Django 5.0.2 on 2025-08-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_allergies_list_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="allergies_list",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="allergies_other",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="dermatological_conditions",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="dermatological_other",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="objectives",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="product_style",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="routine_frequency",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="routine_type",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="skin_concerns_list",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("18-25", "18-25"),
                    ("26-35", "26-35"),
                    ("36-45", "36-45"),
                    ("46-55", "46-55"),
                    ("55+", "55+"),
                ],
                max_length=10,
            ),
        ),
    ]
