# Generated by Django 5.0.2 on 2025-08-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_userprofile_allergies_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="allergies",
            field=models.TextField(
                blank=True, help_text="Allergies connues (JSON format)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="allergies_other",
            field=models.CharField(
                blank=True, help_text="Autre allergie", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dermatological_conditions",
            field=models.TextField(
                blank=True, help_text="Pathologies dermatologiques (JSON format)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dermatological_other",
            field=models.CharField(
                blank=True, help_text="Autre pathologie dermatologique", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="objectives",
            field=models.TextField(
                blank=True, help_text="Objectifs principaux (JSON format)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="product_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("natural", "Bio / Naturel"),
                    ("pharmacy", "Pharmacie / Dermatologique"),
                    ("luxury", "Luxe / Haut de gamme"),
                    ("minimalist", "Minimaliste"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="routine_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("quick", "Rapide (≤ 5 min)"),
                    ("standard", "Standard (10–20 min)"),
                    ("comprehensive", "Complète (20–30 min)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="routine_type",
            field=models.CharField(
                choices=[
                    ("morning", "Matin"),
                    ("evening", "Soir"),
                    ("custom", "Personnalisée"),
                ],
                default="morning",
                help_text="Type de routine préféré",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under18", "Moins de 18 ans"),
                    ("18-25", "18–25 ans"),
                    ("26-35", "26–35 ans"),
                    ("36-45", "36–45 ans"),
                    ("46-60", "46–60 ans"),
                    ("60plus", "60+ ans"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="skin_concerns",
            field=models.TextField(
                blank=True, help_text="Problèmes de peau (JSON format)"
            ),
        ),
    ]
