# Generated by Django 5.0.2 on 2025-09-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_allergies_userprofile_allergies_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('', 'Non spécifié'), ('normal', 'Normal'), ('dry', 'Sèche'), ('oily', 'Grasse'), ('combination', 'Mixte'), ('sensitive', 'Sensible')], default='', max_length=50),
        ),
    ]
