# Generated by Django 5.0.2 on 2025-09-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_skin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='severity',
            field=models.CharField(choices=[('mild', 'Légère'), ('moderate', 'Modérée'), ('severe', 'Sévère')], default='mild', max_length=10),
        ),
    ]
