# Generated by Django 5.0.2 on 2025-08-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_routines", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
