# Generated by Django 5.0.2 on 2025-08-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_routines", "0003_chatmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
