# Generated by Django 5.0.2 on 2025-09-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_routines', '0004_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skincondition',
            name='name',
            field=models.CharField(choices=[('', 'Non spécifié'), ('acne', 'Acné'), ('aging', 'Vieillissement'), ('dryness', 'Sécheresse'), ('oiliness', 'Grasse'), ('sensitivity', 'Sensibilité'), ('hyperpigmentation', 'Hyperpigmentation'), ('rosacea', 'Rosacée'), ('eczema', 'Eczéma'), ('combination', 'Mixte'), ('normal', 'Normal')], max_length=50),
        ),
    ]
