# Generated by Django 5.0.2 on 2025-08-23 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("barcode", "Barcode Scan"),
                            ("image", "Image Upload"),
                            ("manual", "Manual Entry"),
                        ],
                        max_length=10,
                    ),
                ),
                ("barcode", models.CharField(blank=True, max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="scans/")),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("product_name", models.CharField(blank=True, max_length=200)),
                ("product_brand", models.CharField(blank=True, max_length=100)),
                ("product_description", models.TextField(blank=True)),
                ("product_ingredients_text", models.TextField(blank=True)),
                (
                    "product_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("product_risk_level", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scanned_at"],
            },
        ),
    ]
