# Generated by Django 5.0.2 on 2025-09-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='analysis_available',
            field=models.BooleanField(default=False),
        ),
    ]
