# Generated by Django 5.0.2 on 2025-09-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_scan_analysis_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('data_type', models.CharField(choices=[('product_info', 'Informations Produit'), ('ingredient_analysis', 'Analyse Ingrédients'), ('barcode_lookup', 'Recherche Code-barres'), ('ai_analysis', 'Analyse IA'), ('safety_score', 'Score de Sécurité')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['cache_key'], name='scans_produ_cache_k_9eac0a_idx'), models.Index(fields=['data_type'], name='scans_produ_data_ty_daa4c3_idx'), models.Index(fields=['expires_at'], name='scans_produ_expires_4b9395_idx')],
            },
        ),
    ]
