# Generated by Django 5.0.2 on 2025-09-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_productcache'),
    ]

    operations = [
    ]
