# Generated by Django 5.0.2 on 2025-09-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_add_product_cache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcache',
            options={'ordering': ['-last_accessed'], 'verbose_name': 'Cache Produit', 'verbose_name_plural': 'Caches Produits'},
        ),
        migrations.AlterField(
            model_name='productcache',
            name='access_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de fois que ce cache a été consulté'),
        ),
        migrations.AlterField(
            model_name='productcache',
            name='cache_key',
            field=models.CharField(db_index=True, help_text='Clé unique pour identifier le cache (ex: barcode_123456789)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productcache',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date de création du cache'),
        ),
        migrations.AlterField(
            model_name='productcache',
            name='data',
            field=models.JSONField(help_text='Données mises en cache (analyse complète, informations produit, etc.)'),
        ),
        migrations.AlterField(
            model_name='productcache',
            name='data_type',
            field=models.CharField(choices=[('product_info', 'Informations Produit'), ('ingredient_analysis', 'Analyse Ingrédients'), ('barcode_lookup', 'Recherche Code-barres'), ('ai_analysis', 'Analyse IA'), ('safety_score', 'Score de Sécurité'), ('complete_analysis', 'Analyse Complète')], help_text='Type de données mises en cache', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcache',
            name='expires_at',
            field=models.DateTimeField(help_text="Date d'expiration du cache"),
        ),
        migrations.AlterField(
            model_name='productcache',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, help_text='Dernière consultation du cache'),
        ),
        migrations.AddIndex(
            model_name='productcache',
            index=models.Index(fields=['last_accessed'], name='scans_produ_last_ac_e9b28b_idx'),
        ),
    ]
