# Generated by Django 5.0.2 on 2025-09-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_alter_productcache_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCache',
        ),
    ]
