# Generated by Django 5.0.2 on 2025-09-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_remove_product_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Unique cache key for the stored data', max_length=255, unique=True)),
                ('data', models.JSONField(help_text='Cached data in JSON format')),
                ('data_type', models.CharField(choices=[('product_info', 'Product Information'), ('ingredient_analysis', 'Ingredient Analysis'), ('barcode_lookup', 'Barcode Lookup'), ('ai_analysis', 'AI Analysis'), ('safety_score', 'Safety Score'), ('complete_analysis', 'Complete Analysis')], help_text='Type of cached data', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the cache entry was created')),
                ('expires_at', models.DateTimeField(help_text='When the cache entry expires')),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this cache entry has been accessed')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time this cache entry was accessed')),
            ],
            options={
                'verbose_name': 'Product Cache',
                'verbose_name_plural': 'Product Caches',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['cache_key'], name='scans_produ_cache_k_9eac0a_idx'), models.Index(fields=['data_type'], name='scans_produ_data_ty_daa4c3_idx'), models.Index(fields=['expires_at'], name='scans_produ_expires_4b9395_idx')],
            },
        ),
    ]
