# Generated by Django 5.0.2 on 2025-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_remove_product_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data_type', models.CharField(choices=[('complete_analysis', 'Complete Analysis'), ('product_info', 'Product Information'), ('ai_analysis', 'AI Analysis'), ('safety_score', 'Safety Score'), ('ingredient_analysis', 'Ingredient Analysis'), ('barcode_lookup', 'Barcode Lookup')], max_length=20)),
                ('cached_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['cache_key'], name='scans_produ_cache_k_9eac0a_idx'), models.Index(fields=['data_type'], name='scans_produ_data_ty_daa4c3_idx'), models.Index(fields=['expires_at'], name='scans_produ_expires_4b9395_idx')],
            },
        ),
    ]
